import { FEDERAL_STUDENT_AID_IDR_FORM_URL, POLICY_EVIDENCE_CORPUS, POLICY_SNAPSHOT } from "./constants.ts";
import type { AdvisorConsultationIntent, ConsultationHistoryTurnV1, KnowledgeAudience, KnowledgeItemV1, KnowledgePackV1 } from "./types.ts";

export const KNOWLEDGE_PACK_VERSION = "2026-09-08-v1";
const REVIEWED_AT = "2026-09-08";
const official = (id:string,title:string,content:string,sourceUrl:string,keywords:string[],hash:string,programs:string[]=[]):KnowledgeItemV1 => ({id,packId:"official-federal-policy",packVersion:KNOWLEDGE_PACK_VERSION,title,content,authorityTier:"official_federal",sourceKind:"official_web",sourceUrl,sourceLocator:title,policySnapshot:POLICY_SNAPSHOT,reviewedAt:REVIEWED_AT,contentHash:hash,programs,loanFamilies:[],keywords,audiences:["advisor","borrower"],allowedUses:["policy_explanation","case_interview","workflow_guidance"]});
const specialty = (id:string,title:string,content:string,keywords:string[],hash:string):KnowledgeItemV1 => ({id,packId:"specialty-advisor-practice",packVersion:KNOWLEDGE_PACK_VERSION,title,content,authorityTier:"accepted_specialty",sourceKind:"accepted_internal",sourceLocator:"Accepted advisor-practice knowledge",reviewedAt:REVIEWED_AT,contentHash:hash,programs:[],loanFamilies:[],keywords,audiences:["advisor"],allowedUses:["case_interview","workflow_guidance","comparison_explanation","evidence_guidance"]});
const inherited:KnowledgeItemV1[] = POLICY_EVIDENCE_CORPUS.map((e)=>({id:`official-${e.id}`,packId:"official-federal-policy",packVersion:KNOWLEDGE_PACK_VERSION,title:e.title,content:e.content,authorityTier:"official_federal",sourceKind:"official_web",sourceUrl:e.sourceUrl,sourceLocator:e.locator,policySnapshot:e.policySnapshot,reviewedAt:REVIEWED_AT,contentHash:e.contentHash,programs:[],loanFamilies:[],keywords:[...e.keywords],audiences:["advisor","borrower"],allowedUses:["policy_explanation","comparison_explanation"]}));
const officialItems:KnowledgeItemV1[]=[...inherited,
 official("official-pslf-basics","PSLF qualifying framework","Public Service Loan Forgiveness can forgive remaining eligible Direct Loan balances after 120 qualifying monthly payments while the borrower works full-time for an eligible government or not-for-profit employer. Verify employer eligibility and qualifying-payment counts through StudentAid.gov; chat never calculates PSLF credit.","https://studentaid.gov/articles/student-loan-forgiveness/",["pslf","public service","120 payments","qualifying employer"],"de4166f1b93416cc61daae111d52565667ebca009d3199ffee68aef20c84c1d0",["PSLF"]),
 official("official-pslf-progress","PSLF employment and payment tracking","Use Federal Student Aid's PSLF Help Tool and StudentAid.gov to certify qualifying employment and track eligible and qualifying payment counts. Employer eligibility depends on program requirements, not job title alone; chat must not invent qualifying-payment credit.","https://studentaid.gov/articles/manage-your-pslf-progress/",["pslf","employment certification","payment count","help tool"],"95c48f6625b42ffbc7e2552915c5ebbec99a132d01abbc6409012f9bd27c0566",["PSLF"]),
 official("official-default-resolution","Federal loan default resolution","Federal Student Aid identifies rehabilitation and Direct Consolidation as distinct pathways that can resolve federal student loan default. Chat may explain these options but must direct borrowers to current official instructions rather than treating conversation as enrollment.","https://studentaid.gov/articles/default/",["default","rehabilitation","consolidation","collections"],"01ada88fcf22e929973afe92c2232db68abc39419505a5dd04f18935f362c1e6"),
 official("official-idr-recertification","IDR recertification","Current Federal Student Aid IDR materials require applicable borrowers to recertify income and family-size information on the required schedule. Recertification can change future payments, so a current deterministic estimate must not be presented as a guaranteed future payment.",FEDERAL_STUDENT_AID_IDR_FORM_URL,["recertification","income","family size","idr"],"d8a2d219a5042b6de620d061378d5d969643682dc71e1b48989cb50fb6a1f05d")];
const specialtyItems:KnowledgeItemV1[]=[
 specialty("specialty-provenance","Keep fact provenance visible","Distinguish borrower-stated facts, imported StudentAid facts, documented evidence, deterministic calculations, and advisory interpretation. Model inference is never a saved or verified client fact.",["provenance","evidence","verified","imported"],"c09c2a3861691ab4c051e034047761fc7d33c12befb482d4c78053ede517686d"),
 specialty("specialty-case-interview","Ask the smallest useful follow-up","When a material fact is missing or ambiguous, prefer one focused follow-up question that would change the recommendation or eligibility review instead of repeating a full intake checklist.",["missing","ambiguous","follow up","intake"],"88beab7a5c4c98d07ba39c416b8d0c8f955a0e9ae162fa803be47a2107dfb063"),
 specialty("specialty-comparison","Explain deterministic comparisons","Lead with the borrower's objective and deterministic comparison, then explain tradeoffs, assumptions, timing, and unresolved eligibility. A model cannot declare a plan best; FLRs remains a deterministic unique-lowest-payment rule.",["comparison","tradeoff","flrs","lowest payment"],"ceae03158eebdba2b25daf7d519758a6ac8fccb75289b20f987cbed0ee6a8095"),
 specialty("specialty-servicer","Confirm operational steps","Servicer operational steps and document requests can vary. Chat may flag likely follow-up but should say when current servicer or Federal Student Aid instructions must be confirmed before acting.",["servicer","documents","workflow","confirm"],"a8cdd517d7866b88a6b9cc187c66c1a9c06dd7a48744db1ec4d37839e3646635")];
export const OFFICIAL_KNOWLEDGE_PACK:KnowledgePackV1={schema:"student-loan-idr-knowledge-pack-v1",packId:"official-federal-policy",version:KNOWLEDGE_PACK_VERSION,authorityTier:"official_federal",title:"Reviewed federal policy knowledge",reviewedAt:REVIEWED_AT,items:officialItems};
export const SPECIALTY_KNOWLEDGE_PACK:KnowledgePackV1={schema:"student-loan-idr-knowledge-pack-v1",packId:"specialty-advisor-practice",version:KNOWLEDGE_PACK_VERSION,authorityTier:"accepted_specialty",title:"Accepted advisor practice knowledge",reviewedAt:REVIEWED_AT,items:specialtyItems};
export const KNOWLEDGE_PACKS:readonly KnowledgePackV1[]=[OFFICIAL_KNOWLEDGE_PACK,SPECIALTY_KNOWLEDGE_PACK];
const expand:Record<string,string[]>={pslf:["public","service","forgiveness","employer"],default:["rehabilitation","consolidation"],consolidate:["consolidation","ffel","perkins","parent","plus"],payment:["monthly","repayment","idr"],recertify:["recertification","income","family"],evidence:["document","provenance","verified"]};
function words(v:string){return new Set(v.toLowerCase().replace(/[^a-z0-9+]+/g," ").split(/\s+/).filter((x)=>x.length>1));}
function score(item:KnowledgeItemV1,q:string,intent:AdvisorConsultationIntent){const a=words(`${q} ${intent.replace(/_/g," ")}`);for(const t of [...a])for(const x of expand[t]??[])a.add(x);const b=words(`${item.title} ${item.content} ${item.keywords.join(" ")}`);let n=item.authorityTier==="official_federal"?1:0;for(const t of a)if(b.has(t))n+=t.length>=5?3:1;for(const k of item.keywords)if(k.length>=4&&q.toLowerCase().includes(k))n+=6;return n;}
export function retrieveKnowledge(input:{question:string;intent:AdvisorConsultationIntent;audience:KnowledgeAudience;history?:ConsultationHistoryTurnV1[];limit?:number}){const history=(input.history??[]).slice(-6).filter((t)=>t.role==="user").map((t)=>t.content).join(" "),q=`${history} ${input.question}`,limit=Math.min(Math.max(input.limit??8,1),12);const ranked=KNOWLEDGE_PACKS.flatMap((p)=>p.items).filter((i)=>i.audiences.includes(input.audience)).filter((i)=>i.authorityTier!=="official_federal"||i.policySnapshot===POLICY_SNAPSHOT).map((item)=>({item,n:score(item,q,input.intent)})).sort((a,b)=>b.n-a.n||a.item.id.localeCompare(b.item.id));const selected=ranked.filter((x)=>x.n>1).slice(0,limit).map((x)=>x.item);return selected.length?selected:officialItems.slice(0,Math.min(2,limit));}
export function knowledgeCitationView(i:KnowledgeItemV1){return{id:i.id,title:i.title,authorityTier:i.authorityTier,...(i.sourceUrl?{sourceUrl:i.sourceUrl}:{}),reviewedAt:i.reviewedAt,contentHash:i.contentHash};}
export function validateKnowledgePacks(){const issues:string[]=[],ids=new Set<string>();for(const p of KNOWLEDGE_PACKS)for(const i of p.items){if(ids.has(i.id))issues.push(`${i.id}: duplicate`);ids.add(i.id);if(i.packId!==p.packId||i.packVersion!==p.version||i.authorityTier!==p.authorityTier)issues.push(`${i.id}: pack mismatch`);if(!/^[0-9a-f]{64}$/.test(i.contentHash))issues.push(`${i.id}: bad hash`);if(i.authorityTier==="official_federal"&&(!i.sourceUrl||i.sourceKind!=="official_web"))issues.push(`${i.id}: official source required`);if(i.authorityTier==="accepted_specialty"&&i.sourceKind!=="accepted_internal")issues.push(`${i.id}: specialty source invalid`);}return issues;}
