import { knowledgeCitationView } from "./knowledge.ts";
import type { AdvisorEvidencePacketV1, ConsultationCitationV1, ConsultationHistoryTurnV1, KnowledgeAudience } from "./types.ts";

export const DEFAULT_CONSULTATION_MODEL = "@cf/meta/llama-3.3-70b-instruct-fp8-fast";
export interface AiBinding { run(model:string,input:{messages:Array<{role:"system"|"user"|"assistant";content:string}>;max_tokens?:number;temperature?:number}):Promise<unknown>; }
export interface SynthesisEnv { AI?:AiBinding; CONSULTATION_MODEL?:string; }
export interface GroundedSynthesisResult { synthesisMode:"workers_ai_grounded"|"deterministic_evidence_summary"; answer:string; citations:ConsultationCitationV1[]; model?:{provider:"workers-ai";model:string}; fallbackReason?:string; }

function aiText(value:unknown):string|undefined{if(typeof value==="string")return value; if(!value||typeof value!=="object")return undefined;const v=value as Record<string,unknown>;if(typeof v.response==="string")return v.response;if(v.result&&typeof v.result==="object"&&typeof (v.result as Record<string,unknown>).response==="string")return (v.result as Record<string,string>).response;return undefined;}
function boundedHistory(history:ConsultationHistoryTurnV1[]|undefined){return (history??[]).slice(-6).filter((t)=>t.content.trim()).map((t)=>({role:t.role,content:t.content.trim().slice(0,1600)}));}
function modelEvidence(packet:AdvisorEvidencePacketV1){const action=packet.deterministic.nextBestAction;return {policySnapshot:packet.policySnapshot,intent:packet.intent,facts:packet.facts.slice(0,30),missingInformation:packet.missingInformation.slice(0,20),deterministic:{caseContext:packet.deterministic.caseContext,...(packet.deterministic.intelligence?{intelligence:packet.deterministic.intelligence}:{}),...(packet.deterministic.comparison?{comparison:packet.deterministic.comparison}:{}),...(action?{nextBestAction:{primaryState:action.primaryState,nextBestAction:action.nextBestAction,signals:action.signals.slice(0,5).map((s)=>({state:s.state,label:s.label,reason:s.reason,attention:s.attention,dueDate:s.dueDate}))}}:{})},knowledge:packet.knowledge.map((k)=>({id:k.id,title:k.title,authorityTier:k.authorityTier,content:k.content,sourceLocator:k.sourceLocator,sourceUrl:k.sourceUrl,reviewedAt:k.reviewedAt})),warnings:packet.warnings.slice(0,20)};}
function citedIds(answer:string){return [...answer.matchAll(/\[([a-z0-9][a-z0-9._-]{2,100})\]/gi)].map((m)=>m[1]!);}
function rejectReason(answer:string,allowed:Set<string>,knowledgeCount:number):string|undefined{if(answer.length<20)return "model_answer_too_short";if(answer.length>6000)return "model_answer_too_long";if(/<script\b/i.test(answer))return "model_answer_unsafe_markup";const ids=citedIds(answer),unknown=ids.filter((id)=>!allowed.has(id));if(unknown.length)return "model_unknown_citation";if(knowledgeCount>0&&!ids.some((id)=>allowed.has(id)))return "model_missing_citation";return undefined;}
export async function synthesizeGrounded(input:{env:SynthesisEnv;packet:AdvisorEvidencePacketV1;audience:KnowledgeAudience;history?:ConsultationHistoryTurnV1[];deterministicFallback:string}):Promise<GroundedSynthesisResult>{const citations=input.packet.knowledge.map(knowledgeCitationView),fallback=(reason:string):GroundedSynthesisResult=>({synthesisMode:"deterministic_evidence_summary",answer:input.deterministicFallback,citations,fallbackReason:reason});if(!input.env.AI)return fallback("ai_binding_unavailable");const model=input.env.CONSULTATION_MODEL?.trim()||DEFAULT_CONSULTATION_MODEL;const system=`You are the conversational synthesis layer for a professional federal student-loan advisory calculator. Use ONLY supplied deterministic evidence and Knowledge Pack items. Deterministic code is authoritative for repayment math, eligibility, chronology, and saved case facts. Never invent or change those results. Never claim a specialty/advisor item is federal authority. Never imply that your response enrolls, files, signs, verifies, or mutates anything. If a material fact is missing, say so and ask at most one focused follow-up question. Cite factual policy/advisor-knowledge claims inline using exact Knowledge Pack IDs in square brackets, such as [official-pslf-basics]. Do not create citation IDs. Audience: ${input.audience}.`;const messages:[{role:"system";content:string},...Array<{role:"user"|"assistant";content:string}>]=[{role:"system",content:system},...boundedHistory(input.history),{role:"user",content:`Question: ${input.packet.question}\nEvidence packet: ${JSON.stringify(modelEvidence(input.packet))}`}];try{const raw=await input.env.AI.run(model,{messages,max_tokens:700,temperature:0.2}),answer=aiText(raw)?.trim();if(!answer)return fallback("model_empty_response");const allowed=new Set(input.packet.knowledge.map((k)=>k.id)),reason=rejectReason(answer,allowed,input.packet.knowledge.length);if(reason)return fallback(reason);const used=new Set(citedIds(answer));return{synthesisMode:"workers_ai_grounded",answer,citations:citations.filter((c)=>used.has(c.id)),model:{provider:"workers-ai",model}};}catch{return fallback("model_request_failed");}}
